language: python
python:
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=sythe -m unittest discover -v -s "." -p "*test*.py"
  - pylint --rcfile pylint.rc sythe

after_success:
  - coveralls
